# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import catan_pb2 as catan__pb2


class CatanServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateGame = channel.unary_unary(
        '/soc.protos.CatanServer/CreateGame',
        request_serializer=catan__pb2.CreateGameRequest.SerializeToString,
        response_deserializer=catan__pb2.CreateGameResponse.FromString,
        )
    self.StartGame = channel.unary_unary(
        '/soc.protos.CatanServer/StartGame',
        request_serializer=catan__pb2.StartGameRequest.SerializeToString,
        response_deserializer=catan__pb2.StartGameResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/soc.protos.CatanServer/Subscribe',
        request_serializer=catan__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=catan__pb2.GameMessage.FromString,
        )
    self.TakeAction = channel.unary_unary(
        '/soc.protos.CatanServer/TakeAction',
        request_serializer=catan__pb2.TakeActionRequest.SerializeToString,
        response_deserializer=catan__pb2.MoveResponse.FromString,
        )


class CatanServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateGame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartGame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TakeAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CatanServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateGame': grpc.unary_unary_rpc_method_handler(
          servicer.CreateGame,
          request_deserializer=catan__pb2.CreateGameRequest.FromString,
          response_serializer=catan__pb2.CreateGameResponse.SerializeToString,
      ),
      'StartGame': grpc.unary_unary_rpc_method_handler(
          servicer.StartGame,
          request_deserializer=catan__pb2.StartGameRequest.FromString,
          response_serializer=catan__pb2.StartGameResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=catan__pb2.SubscribeRequest.FromString,
          response_serializer=catan__pb2.GameMessage.SerializeToString,
      ),
      'TakeAction': grpc.unary_unary_rpc_method_handler(
          servicer.TakeAction,
          request_deserializer=catan__pb2.TakeActionRequest.FromString,
          response_serializer=catan__pb2.MoveResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'soc.protos.CatanServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
